version: '3'

networks:
  pahome-network:
    driver: bridge

services:
  application:
    build:
      context: .
    ports:
      - "8000:8000"
    networks:
      - pahome-network
  postgres:
    image: postgres:13.4-alpine
    networks:
      - pahome-network
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
    volumes:
      - ./docker/persist/postgres/data:/var/lib/postgresql/data
      - ./docker/config/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
#  redis:
#    image: redis:6-alpine
#    ports:
#      - "6379:6379"
#    command: redis-server --save 60 1
#    volumes:
#      - "./docker-temp/redis:/data"